VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "EnumInterface"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function getNome(ByVal num As Integer) As String
End Function

Public Function getNum(ByVal nome As String) As Integer
End Function

Public Function getArray() As Variant
End Function


